# # import datetime

# #cách 1
# import smtplib
# from email.mime.multipart import MIMEMultipart
# from email.mime.text import MIMEText
# import datetime
# # Thông tin người gửi và thông tin đăng nhập
# sender_email = "nhat.thivan.hcm@gmail.com"
# sender_password = "thivannhat1108"

# # Thông tin người nhận và tiêu đề email
# receiver_email = "thivannhat111@gmail.com"
# subject = "Test Email"

# # Nội dung email
# body = "Hello, this is a test email!"

# # Tạo đối tượng MIMEMultipart để chứa nội dung email
# message = MIMEMultipart()
# message['From'] = sender_email
# message['To'] = receiver_email
# message['Subject'] = subject

# # Thêm nội dung email vào đối tượng MIMEMultipart
# message.attach(MIMEText(body, 'plain'))

# # Kết nối đến máy chủ email và đăng nhập
# server = smtplib.SMTP('smtp.gmail.com', 587)
# server.starttls()
# server.login(sender_email, sender_password)
# # Gửi email
# text = message.as_string()
# server.sendmail(sender_email, receiver_email, text)

# # Đóng kết nối
# server.quit()

# print("Email đã được gửi thành công!")

#---------------------------------------------------------------------------------------------------------------------------
#cách 2
# import smtplib
# from email.mime.text import MIMEText
# from email.mime.multipart import MIMEMultipart

# # Thông tin tài khoản email của người gửi
# sender_email = "your_email@example.com"
# sender_password = "your_email_password"

# # Thông tin người nhận và nội dung email
# receiver_email = "recipient_email@example.com"
# subject = "Subject of the email"
# body = "Content of the email."

# # Khởi tạo đối tượng MIMEMultipart
# message = MIMEMultipart()
# message["From"] = sender_email
# message["To"] = receiver_email
# message["Subject"] = subject

# # Thêm nội dung email vào đối tượng MIMEMultipart
# message.attach(MIMEText(body, "plain"))

# # Kết nối đến máy chủ SMTP của Outlook
# with smtplib.SMTP("smtp.office365.com", 587) as server:
#     server.starttls()
#     server.login(sender_email, sender_password)
#     text = message.as_string()
#     server.sendmail(sender_email, receiver_email, text)


#-----------------------------------------------------------------------------------------------------

# def is_valid_date(day, month, year):
#     try:
#         datetime.datetime(year=year, month=month, day=day)
#         return True
#     except ValueError:
#         return False
    
# a = is_valid_date(28,2,2023)

# print(a)

# from fastapi import FastAPI, HTTPException, Depends
# from pydantic import BaseModel, validator
# from datetime import datetime

# app = FastAPI()

# class UserCreate(BaseModel):
#     date: str
    
#     @validator('date')
#     def validate_date(cls, value):
#         try:
#             datetime.date(value, '%d/%m/%Y')
#             return value
#         except ValueError:
#             raise ValueError("Bạn đã nhập ngày tháng không hợp lệ!")
        
# @app.post("/users/")
# async def create_user(user: UserCreate):
#     # do something with the validated date
#     return {"message": "User created"}

import smtplib, ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from socket import gaierror

#mail: its@tbslogistics.com 
#pass:    i)$sdH(c9O,M gửi e
port = 465
smtp_server = "pro201.emailserver.vn" #
login = "its@tbslogistics.com" # paste your login generated by Mailtrap
password = "i)$sdH(c9O,M" # paste your password generated by Mailtrap
sender_email = "its@tbslogistics.com"
receiver_email = ['nhat.thivan.hcm@gmail.com', 'nhat.thi@tbslogistics.com']#'hongthai@gmail.com','hongthai.pham@tbslogistics.com'
message = MIMEMultipart("alternative")
message["Subject"] = "TBS Logistics Auto Mailer"
message["From"] = sender_email
message["To"] = ';'.join(receiver_email)
# write the text/plain part
text = """\
Hi,
Check out the new post on the Mailtrap blog:
SMTP Server for Testing: Cloud-based or Local?
https://blog.mailtrap.io/2018/09/27/cloud-or-local-smtp-server/
Feel free to let us know what content would be useful for you!"""
# write the HTML part
html = """\
<html>
  <body>
    <p>Hi,<br>
       Check out the new post on the Mailtrap blog:</p>
    <p><a href="https://blog.mailtrap.io/2018/09/27/cloud-or-local-smtp-server">SMTP Server for Testing: Cloud-based or Local?</a></p>
    <p> Feel free to <strong>let us</strong> know what content would be useful for you!</p>
  </body>
</html>
"""
# convert both parts to MIMEText objects and add them to the MIMEMultipart message
part1 = MIMEText(text, "plain")
part2 = MIMEText(html, "html")
message.attach(part1)
message.attach(part2)
# send your email
#with smtplib.SMTP(smtp_server, port) as server:

context = ssl.create_default_context()

try:
    #send your message with credentials specified above
    with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
        server.login(login, password)
        server.sendmail(
            sender_email, receiver_email, message.as_string()
        )
    # tell the script to report if your message was sent or which errors need to be fixed 
    print('Sent')
except (gaierror, ConnectionRefusedError):
    print('Failed to connect to the server. Bad connection settings?')
except smtplib.SMTPServerDisconnected:
    print('Failed to connect to the server. Wrong user/password?')
except smtplib.SMTPException as e:
    print('SMTP error occurred: ' + str(e))